version: '3.0'

services:
  # nginx to host frontend
  nginx:
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    volumes:
      # Replace default.conf file with our own
      - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
      # Volume used to build frontend (used as document root)
      - abot-build:/app/abot-frontend
    ports:
      - "${SERVER_PORT}:80"
    networks:
      - my-network
    depends_on:
      - frontend

  # Frontend (build-only)
  frontend:
    image: abot/frontend
    build:
      context: ./abot-frontend/
      dockerfile: Dockerfile.prod
    volumes:
      - abot-build:/app

  # Actions server
  actions:
    image: abot/actions
    build:
      context: ./abot-rasa/
      dockerfile: ./Dockerfile.actions
    networks:
      - my-network

  # Backend for API endpoints and Chatbot model runner
  backend:
    image: abot/backend
    environment:
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      ENDPOINTS_FILE: ${ENDPOINTS_FILE}
      CREDENTIALS_FILE: ${CREDENTIALS_FILE}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    build:
      context: ./abot-backend/
      dockerfile: ./Dockerfile.prod
    ports:
      - "${BACKEND_PORT}:8080"
    networks:
      - my-network

volumes:
  abot-build:

networks:
  my-network:
