version: '3.0'

services:
  # nginx to host frontend
  nginx:
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    volumes:
      # Replace default.conf file with our own
      - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
      # Volume used to build frontend (used as document root)
      - build_vol:/app/abot-frontend
    ports:
      - $SERVER_PORT:80
    networks:
      - my-network
    depends_on:
      - frontend

  # Frontend (build-only)
  frontend:
    image: abot/frontend
    build:
      context: ./abot-frontend/
      dockerfile: Dockerfile.prod
      args:
        - "REACT_APP_API_ENDPOINT=$REACT_APP_API_ENDPOINT"
    volumes:
      - build_vol:/app

  # Rasa server
  rasa:
    image: abot/rasa
    environment:
      - TELEGRAM_BOT_TOKEN
      - RASA_ACTION_ENDPOINT
      - RASA_DUCKLING_HTTP_URL
      - "POSTGRESQL_SCHEMA=$RASA_TRACKER_STORE_PGSQL_SCHEMA"
      - RASA_TRACKER_DB_URI
    command:
      - run
      - "--endpoints"
      - "endpoints.test.yml"
      - "--credentials"
      - "credentials.test.yml"
      - "-vv"
    build:
      context: ./abot-rasa/
      dockerfile: ./Dockerfile.rasa
    networks:
      - my-network
    expose:
      - 5005

  # Actions server
  actions:
    image: abot/actions
    environment:
    - BACKEND_ENDPOINT_BASE
    - RASA_DUCKLING_HTTP_URL
    build:
      context: ./abot-rasa/
      dockerfile: ./Dockerfile.actions
    networks:
      - my-network
    expose:
      - 5055

  # Backend for API endpoints and Chatbot model runner
  backend:
    image: abot/backend
    environment:
      - WEB_CONCURRENCY
      - RASA_REST_ENDPOINT_BASE
      - ACTIONS_ENDPOINT_BASE
      - "DB_URI=$BACKEND_DB_URI"
    build:
      context: ./abot-backend/
      dockerfile: ./Dockerfile.prod
    ports:
      - "$BACKEND_PORT:8080"
    expose:
      - 8080
    networks:
      - my-network
    depends_on:
      - postgres

  # Duckling server
  duckling:
    image: rasa/duckling
    expose:
      - 8000
    ports:
      - "8092:8000"
    networks:
      - my-network

  # Postgres Database
  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "$POSTGRES_PORT:5432"
    expose:
      - 5432
    networks:
      - my-network

volumes:
  build_vol:

networks:
  my-network:
