version: '3.0'
services:
  abot_actions:
    image: abot/actions
    build:
      dockerfile: ./abot-rasa/Dockerfile.actions
  frontend:
    image: abot/frontend
    build:
      dockerfile: ./abot-frontend/Dockerfile.prod
  backend:
    image: abot/backend
    build: ./abot-backend
